CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y # connection and security experimental features
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#usuallfy 5 but +1 for split
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

CONFIG_ZMK_IDLE_TIMEOUT=30000 #30000 default values in ms
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000 # 900000 default values in ms
